#!/bin/sh

script=$0
if [ -h $script ]; then
   script=`readlink $script`
fi
dir=`dirname $script`

if [ "" = "$HANNIBAL_HBASE_VERSION" ]; then
    HANNIBAL_HBASE_VERSION="0.90"
    echo "building Hannibal for HBase $HANNIBAL_HBASE_VERSION (may be altered by assigning 0.90, 0.92, 0.94, 0.96 or 0.98 to HANNIBAL_HBASE_VERSION)"
else
    echo "building Hannibal for HBase $HANNIBAL_HBASE_VERSION (as defined by HANNIBAL_HBASE_VERSION)"
fi

$dir/activator clean compile assets
res1=$?

$dir/activator doc
res2=$?

if [ "0 0" = "$res1 $res2"  ]; then
    echo "**** Hannibal READY! Start with ./start"
else
    echo "Wooops! It seams that there was a problem building Hannibal, please report to https://github.com/sentric/hannibal/issues"
fi

