#!/bin/sh

script=$0
if [ -h $script ]; then
   script=`readlink $script`
fi
dir=`dirname $script`

if [ "" = "$HANNIBAL_HBASE_VERSION" ]; then
    HANNIBAL_HBASE_VERSION="0.90"
    echo "building Hannibal for HBase $HANNIBAL_HBASE_VERSION (may be altered by assigning 0.90, 0.92 or 0.94 to HANNIBAL_HBASE_VERSION")"
else
    echo "building Hannibal for HBase $HANNIBAL_HBASE_VERSION (as defined by HANNIBAL_HBASE_VERSION)"
fi

$dir/sbt clean compile
