#!/bin/sh
script=$0
if [ -h $script ]; then
    script=`readlink $script`
fi
dir=`dirname $script`

export PATH="/usr/lib/jvm/java-8-oracle-amd64:$PATH"
hannibal_dir="`cd $dir; pwd`"

./sbt clean
HANNIBAL_HBASE_VERSION=1.1.3 ./create_package
mkdir -p deploy/hbase113
cp target/hannibal-hbase*.tgz deploy/hbase113
