#!/bin/sh

script=$0
if [ -h $script ]; then
    script=`readlink $script`
fi
dir=`dirname $script`

if [ -d $dir/target ]; then
    java -jar $dir/sbt-launch-0.11.3.jar -DapplyEvolutions.default=true start
else
    echo "The project has not yet been built, please run './build' first"
fi