#!/bin/sh

script=$0
if [ -h $script ]; then
    script=`readlink $script`
fi
dir=`dirname $script`

if [ -f $dir/target/start ]; then
    $dir/target/start -DapplyEvolutions.default=true
else
    echo "The project has not been built yet, please run './build' first"
fi